version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/mockdata
      - ./scripts:/docker-entrypoint-initdb.d

    

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080